dir: '{{.InterfaceDir}}/{{.SrcPackageName}}mock'
filename: mocks.go
force-file-write: true
structname: '{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}mock'
template: testify
packages:
  github.com/slok/simple-ingress-external-auth/internal/app/auth: {interfaces: {TokenGetter}}