// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authmock

import (
	"context"

	"github.com/slok/simple-ingress-external-auth/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenGetter creates a new instance of TokenGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGetter {
	mock := &TokenGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenGetter is an autogenerated mock type for the TokenGetter type
type TokenGetter struct {
	mock.Mock
}

type TokenGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenGetter) EXPECT() *TokenGetter_Expecter {
	return &TokenGetter_Expecter{mock: &_m.Mock}
}

// GetStaticTokenValidation provides a mock function for the type TokenGetter
func (_mock *TokenGetter) GetStaticTokenValidation(ctx context.Context, tokenValue string) (*model.StaticTokenValidation, error) {
	ret := _mock.Called(ctx, tokenValue)

	if len(ret) == 0 {
		panic("no return value specified for GetStaticTokenValidation")
	}

	var r0 *model.StaticTokenValidation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.StaticTokenValidation, error)); ok {
		return returnFunc(ctx, tokenValue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.StaticTokenValidation); ok {
		r0 = returnFunc(ctx, tokenValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.StaticTokenValidation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenGetter_GetStaticTokenValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaticTokenValidation'
type TokenGetter_GetStaticTokenValidation_Call struct {
	*mock.Call
}

// GetStaticTokenValidation is a helper method to define mock.On call
//   - ctx
//   - tokenValue
func (_e *TokenGetter_Expecter) GetStaticTokenValidation(ctx interface{}, tokenValue interface{}) *TokenGetter_GetStaticTokenValidation_Call {
	return &TokenGetter_GetStaticTokenValidation_Call{Call: _e.mock.On("GetStaticTokenValidation", ctx, tokenValue)}
}

func (_c *TokenGetter_GetStaticTokenValidation_Call) Run(run func(ctx context.Context, tokenValue string)) *TokenGetter_GetStaticTokenValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenGetter_GetStaticTokenValidation_Call) Return(staticTokenValidation *model.StaticTokenValidation, err error) *TokenGetter_GetStaticTokenValidation_Call {
	_c.Call.Return(staticTokenValidation, err)
	return _c
}

func (_c *TokenGetter_GetStaticTokenValidation_Call) RunAndReturn(run func(ctx context.Context, tokenValue string) (*model.StaticTokenValidation, error)) *TokenGetter_GetStaticTokenValidation_Call {
	_c.Call.Return(run)
	return _c
}
